### ISSUE TITLE
Queen's Eye Blocks Attacks

### ISSUE THREAD

**Issue by DoomLaser9** [cmss13-devs/cmss13#1053]
## Description

The queen's eye can block pounces on humans that are moving out from under it, and it can also block shoves, grabs, slashes, etc. This seems unintended.

## Difference between expected and actual behavior

The queen's eye should not block pounces on mobs that have just begun moving away from it, and it should not block "direct-click" attacks like shoving/grabbing/slashing.

Basically, there shouldn't be a situation where the queen's eye gets attacked instead of a human that would have otherwise been the recipient of the attack.

There may be a possible relationship to #535.

#### Note: The pounce situation would be a very rare occurrence due to timings involved, but this is how it could be reproduced in a test environment:
1. Be runner/lurker (anything that can pounce).
2. Have human adjacent to you (easier to reproduce if it's north or south).
3. Have queen's eye on human's tile.
4. Hold the mouse over a part of the queen's eye sprite that is also over the human sprite.
5. With attention to timing, push the human away and immediately pounce (e.g. middle-click, at the start of the human sprite movement).
6. Note that the queen's eye gets pounced, even though your mouse was also over the human's sprite.

#### Direct-click attacks:
1. Be xeno.
2. Have human adjacent to you, with queen's eye on top of it.
3. Slash a spot on the human that is covered by the queen's eye, and end up slashing the queen's eye instead of the human.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by realforest2001** [comment]
Confirmed blocking pounces, however I found no instances of this blocking slashes

**Comment by Huffie56** [comment]
@ItsVyzo and @usnpeepoo could you mark this as need reproduction ? thanks

**Comment by Huffie56** [comment]
if this still happened we would hear more about it queen eyes is there all the time.... putting this on cleaning up flag.

**Comment by ihatethisengine** [comment]
It does still happen. Happened to me few weeks ago, happened to another lurker literally yesterday.

**Comment by Huffie56** [comment]
> 

so you can still tackle the queen eyes or pounce it?

**Comment by ihatethisengine** [comment]
You can pounce it. It will stop your pounce (and invis iirc) and apply the post-pounce freeze. It will state in the chat that you pounced at queen's eye. I don't know about tackling, never happened to me.

**Comment by fira** [comment]
From my testing a lot of info here seem to be incorrect:
 * The queen eye doesn't actually block pouncing, it in very specific conditions block the landing tackle if everything lines up
 * In reproduction steps, targeting the queen eye will just prevent you from pouncing, you do not need to overlap sprites
 * In reproduction steps, you do not need to be adjacent
 * In reproduction steps, you do not need anyone else on the tile - and don't need to shuffle them either as a result
aka. there is clear confusion as to what causes this +  how it works

Instead, pouncing a turf with the queen eye on it will simply do it. 
This is apparently just due to `pounced_turf` being dumb and not limited to /mob/living when scanning for turf contents
So what probably actually happens in 90% of cases is that you pounced the queen eye turf missing your target to begin with, and the pounce got relayed to the eye. "Jump" part of the pounce uses completely different mechanics
