### ISSUE TITLE
Impossible 'upload data' objectives

### ISSUE THREAD

**Issue by Mark9013100** [cmss13-devs/cmss13#1222]
## Description

Over multiple rounds, despite getting all intel items (papers, manuals, folders), I've failed to receive passwords for two terminals, thus preventing completion of the 'upload data' objective.

## Difference between expected and actual behavior

For the passwords to be given from intel items.

## Steps to reproduce

Retrieve all intel items, read, count the number of intelligence terminals. This is best done on LV624.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Known issue. It is somewhere on my list, along with getting passwords for terminals that do not actually exist.

**Comment by ThePiachu** [comment]
I think I know what this might be caused by - Objectives only get generated for regular map. If we have any Terminal on a Nightmare Insert, it will get an Objective but the Objective won't have any clues associated with them (so it won't be connected to other things like Folders and so on).

We ought to generate those Clues whenever a new Objective spawns, which might be a bit tricky due to map spawn order not being predictable. I might see what I can do about it soon since I'm currently in the midst of making sure IO stuff works 100%...
