### ISSUE TITLE
TICKET SYSTEM megathread

### ISSUE THREAD

**Issue by stanalbatross** [cmss13-devs/cmss13#1229]
## Description

Drop bugs and feature things regarding the ticket system here (for admins)

potential issues

- hrefs

**Comment by VagabondZero79** [comment]
- More buttons for quick explanations for people

- The ability to defer Ahelps to Mentors

**Comment by ClairionCM** [comment]
Heya! I have a few things that would be awesome to get added to the ticket system. (Although I will say that I'm terrible at coding so if some of these features aren't possible/too hard to implement please do shoot them right down.)

- Vagebond already touched on this a bit but fully getting the autoresponses back for ahelps would be great. If you need someone to help write them to save you the effort I'd be open to help out!

- Currently when a player responds to a PM staff sends them in regards to an ahelp that response shows up in red, regular sized text. Sometimes these messages can be missed because they get confused with either combat that is nearby or alpha/MP comms. (Especially if you're handling multiple ahelps at the same time.) If the text could become larger and a disrupt the normal flow of the chat a bit more that would be great!

- A way to mark ahelps would also be great. I already love that we get a sound when someone else is replying to an ahelp we are trying to reply to but if we could mark the ahelp so people will also get the bloop if the staff member handling it isnt currently replying that would be great. (And a mark button would mean we'd need to be able to unmark the ahelps also.)
Additionally, and this might be impossible, it would be great if it could show what admin marked an ahelp somewhere in the ticket tab would be very nice.

**Comment by Kiara-Miller** [comment]
Id make the fonts 1-3 points bigger for ahelps too.

**Comment by Huffie56** [comment]
hello @ItsVyzo and @usnpeepoo this thread isn't being used and it's a bad way to collect issue or suggestion so i suggest you close it?
maybe move what's inside into the forum?
