### ISSUE TITLE
Consistency issue concerning access on almayer

### ISSUE THREAD

**Issue by Huffie56** [cmss13-devs/cmss13#1448]
## Description
I have checked all the restricted room and check if i could bypass them without any ID. here is my result for lower level:
Some rooms have restricted access via one door but can be bypass via another door that don't has the same restriction.
I have checked all the restricted room and check if i could bypass them. here is my result for lower level:
1-The two atmospherics rooms north and south of lower engi have an engi door but this can be bypass via the maintenance door to their west(just remove the maintenance doors don't need those here).
2-Vehicule crew Bunk can be access via maintenance door east of it.
3-Weapon control room north and south can be access via two maintenance door in each.
4-Lounge or Main kitchen can be access bypass via south maintenance door.
5- delta canteen south as a maintenance door without restriction.
6- alpha canteen north as a maintenance door without restriction.

Also the fact that all the maintenance door can be access without ID seem weird to me. Maintenance door should be only accessible to MT and CE unless CIC remove access require to maintenance.

It may be more efficient to change how Maintenance door work to fix this issues.

## Difference between expected and actual behavior
If a room as restricted access it should be consistent for all the doors leading to it.

## Issue bingo (not required to be all checked)

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
Once upon a time it required CIC to remove access requirements to let everybody into the maintenance. Eventually it got switched to being on by default, so now anybody can enter maintenance whenever, which is probably for the best. It resulted in some weirdness, though.

**Comment by Huffie56** [comment]
i guess it was made so people don't blow up door to loot maintenance? it should at-least require basic USCM access to avoid UPP going around the ship? for example

**Comment by Segrain** [comment]
It was probably to make it easier to hunt shipside xenos, which was the main reason anybody ever removed access requirements from maintenance doors.

As for UPP, all the ERTs have full access everywhere on Almayer. It is that, or we would have to have them blow every door they meet (and give them resources to do so), which is more tedium than anybody really wants.

**Comment by Huffie56** [comment]
> It was probably to make it easier to hunt shipside xenos, which was the main reason anybody ever removed access requirements from maintenance doors.
> 
> As for UPP, all the ERTs have full access everywhere on Almayer. It is that, or we would have to have them blow every door they meet (and give them resources to do so), which is more tedium than anybody really wants.

We could :
1-Keep it as it is.
2-Fix the few maintenance doors i mentions.
3-Remove lot's of access restriction to make it more coherent.
what you think it's best?

**Comment by Herotitan772** [comment]
I don’t see this as a bug at all, most of the alternative ways into areas are significantly longer than the restricted path and most are either in areas that don’t really need restrictions or are common xenos hiding areas

eg. The upper engie maintenance entry is very rarely used maliciously to enter engineering as its very easy to just hack the doors anyways. Locking down this area I can only see restricting fun RP scenarios or becoming a frustrating locked down area that marines end up breaking into anyway so i don’t think it should be changed

Another area is as you said the crewman bunks. I don’t see why this area is Locked down in the first place and the maintenance entry is a really long way to go to get to an area that doesn’t even contain anything of value. Most the time I see people just blowing up the locked door anyway so I don’t think this should be changed

and the last area I can think of is the maintenance access into the kitchen which I REALLY don’t think should be removed because I can really only see it resulting in more destructive entry’s into the kitchen from mainly, research, random marines and MTs. So I really don’t think this should be changed
