### ISSUE TITLE
SEA Spawns with M44 Holster rig but no gun/ammo

### ISSUE THREAD

**Issue by Moonshanks** [cmss13-devs/cmss13#1640]
## Description

What's written on the tin, SEA comes out of cryo with a empty holster.

## Difference between expected and actual behavior

SEA's M44 holster should have a custom M44 and full ammo

## Steps to reproduce

Load into game. Pick SEA, load in after round start.

## Issue bingo (not required to be all checked)

- [ ] Issue could be reproduced at least once
- [X ] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Googles-Hands** [comment]
This is very likely related to my issue #1605, which was specifically fixed by #1611.

This most likely got broken with the sidearm shuffle #1457 which made the Mod 88 the new standard sidearm and removed the custom M44 and custom M4A3 from being vendable/roundstart equipment. You now need to spend customization points to add them to your roundstart loudouts. (Still dislike your PR @spartanbobby, not even tested properly reeee)
