### ISSUE TITLE
Research fuel is bugged

### ISSUE THREAD

**Issue by kiVts** [cmss13-devs/cmss13#1706]
## Testmerges:

There was a few testmerges but I dont remember what is it, I believe its this round
![IMG_20221125_225842](https://user-images.githubusercontent.com/48099872/204071636-72fcf7eb-65a4-4f48-a87f-8fcf7bd881f4.jpg)

## Description

In short, I created research fuel flowing 3 fueling 1 oxi 8 which should be way more satanic then anything else, however. When I lit it on fire, it created a fake fire of one tile which would never go out on its own, it also would never damage you if you walk over it, it didnt set you on fire. it was lit both in simulation (yes, the fire stayed in simulation forever till end of the round) via a nade and beaker bomb in containment, it could be extinguished.

## Difference between expected and actual behavior

Research fuel shouldnt be excellent trolling and scaring (YOU ARE GOING INTO THE FIREPIT BUDDY 🔥)material, it should kill monkeys in 5 seconds.

## Steps to reproduce

Create fuel above, lit on fire, walk over it.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Unknownity** [comment]
Cannot replicate. Said fake fire has never occurred in my tests

**Comment by kiVts** [comment]
Maybe it was caused by testmerges
these was the testmerges iirc 
![image](https://user-images.githubusercontent.com/48099872/204104878-d2c13c66-7a70-4137-90f7-a34f156299a0.png)

**Comment by kiVts** [comment]
obviously only the last one is touching fire

**Comment by RenaRenaRe** [comment]
I witnessed this happen during a round the other day, and have tried reproducing it myself to no avail.
I can definitely vouch for it being a real bug. But yeah it might be related to the fire smothering test merge since I think that was active during the round I witnessed this.

**Comment by RenaRenaRe** [comment]
Oh and to be clear, the exact steps I used to reproduce it were:
Use the Chem Panel "Create custom reagent" to make a chemical with the relevant fire properties.
Take 30u of that chem in a vial and put it in the XRF scanner in research, so that research has now discovered those properties
Use the synthesis simulator to create a new chem with the stats I posted in that image
Use the Chem Panel to "Spawn Reagent in Container"
Take that spawned reagent and put it in a grenade
Put the grenade in the OT simulator or simply detonate it and observe it being broken.

I'm not necessarily saying you have to do all that, the XRF scanner thing was just something I did for convenience, but that's what I did to reproduce it

**Comment by ItsVyzo** [comment]
Resolved
