### ISSUE TITLE
Undefined proc / verb - check_eye()

### ISSUE THREAD

**Issue by ThePiachu** [cmss13-devs/cmss13#1809]
### Testmerges

-

### Description of the bug

```
runtime error: undefined proc or verb /datum/entity/player/check eye().

proc name: handle regular hud updates (/mob/living/carbon/Xenomorph/proc/handle_regular_hud_updates)
  source file: life.dm,253
  usr: null
  src: Mature Ravager (WHY-301) (/mob/living/carbon/Xenomorph/Ravager)
  src.loc: the floor (26,130,3) (/turf/open/shuttle/dropship)
  call stack:
Mature Ravager (WHY-301) (/mob/living/carbon/Xenomorph/Ravager): handle regular hud updates()
Mature Ravager (WHY-301) (/mob/living/carbon/Xenomorph/Ravager): Life(2)
Xeno Life (/datum/controller/subsystem/xeno): fire(0)
Xeno Life (/datum/controller/subsystem/xeno): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

### What's the difference with what should have happened?

Shouldn't get runtime errors.

### How do we reproduce this bug?

???

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
can't find the proc or verb causing the error ("/datum/entity/player/check eye().")
proc name that handle hud update is /mob/living/carbon/xenomorph/proc/handle_regular_hud_updates()
not what's above 
the check eyes is called interactee.check_eye(src)
not what's above.
another is /datum/entity/player_entity/proc/check_eye()
that is called /datum/entity/player/check eye(). in the runtime report above.

since it seem this runtime report doesn't make any sense going to put it under cleanup flag.
sorry if my digging is hard to read/understand.
