### ISSUE TITLE
Table Contents not updating 

### ISSUE THREAD

**Issue by nuklearcellphoneg** [cmss13-devs/cmss13#2080]
### Testmerges

N/A

### Description of the bug

#427 was my initial reporting but recently I realized what's going on.

If objects are removed from a table via a method other than Pick-Up, it causes a sprite to remain on the table despite no object being there. See How to reproduce for how to pick up without Pick-Up.

Another similar but different thing happens when MULTIPLE of the same thing are placed on a table: In my example, I placed multiple Prox-Igniters on a table, and placed them on each corner of the table. IF I then pick one Prox-Igniter OFF the table, its sprite remains until I place it back ON the table, where its sprite immediately updates 

### What's the difference with what should have happened?

Table should update contents by removing sprite.

### How do we reproduce this bug?

1. Take igniter, place on table
2. Take proximity sensor in-hand touch igniter.
3. It becomes a prox-igniter in-hand but leaves its sprite.
4. To remove sprite, disassemble or else replace the igniter.

Alternate way:
1. Place some tools on a table
2. Hold plastic bag in hand
3. Pick up all tools using bag.
4. Sprites remain.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Anthem2000** [comment]
As it was explained to me by harryob, currently (apparently to help with lag) surfaces (anything that you put items on, i.e. tables, racks etc..) work differently in the sense that instead of the item getting placed onto the table like you would normally expect it is actually put into a list of contents that are then rendered as overlays. The issue with this is that in certain situations like when you try and assemble a device with one item on the table and the other one in your hand, the table doesn't rerender once the object is no longer there. This is only one of many scenarios where this happens, I think you found a few others. It's probably noteworthy to say that (from what I have heard) someone is probably going to completely refactor the code and remove the overlay system because the gains in performance are minuscule that it's not even worth it.

**Comment by Huffie56** [comment]
@harryob hello sorry to bother you but i think this isn't an issue but that the overlay system is something you want to remove in the future? so can you close this issue and move this onto the roadmap ?
thanks

**Comment by Segrain** [comment]
Outdated as we ceased merging items onto surfaces some time ago.
