### ISSUE TITLE
Radio backpack bug

### ISSUE THREAD

**Issue by kommikas124** [cmss13-devs/cmss13#2233]
### Testmerges

Yes but not affected

### Description of the bug

The USCM Small Radio Telephone pack has a inventory glitch/ bug as if you hover mouse over one item and click it, it pulls out the item left of it from time to time. 
![Screenshot (119)](https://user-images.githubusercontent.com/96309/210997682-33a61a97-9ecc-47c1-bb4f-59a41e1fd67b.png)
![Screenshot (118)](https://user-images.githubusercontent.com/96309/210997706-1c67e77f-03f2-490f-a1a8-a55842e58e7c.png)

If unable to see pictures, there here is a imgur link: https://imgur.com/a/o2M0uPh

### What's the difference with what should have happened?

You should pull out the item you click on.

### How do we reproduce this bug?

1. wear the USCM small Telephone Pack 
2. Put items like flask, lighter, stamp, dropper and etc in it
3. try taking out the items.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Crowbar764** [comment]
This happens when clicking the background square of an item, which triggers  an index-based search to get the item. Telephone packs are unique in that they have a hidden item (the telephone) inside them at all times as shown in the picture. This hidden item offsets the index search by 1, and thus incorrectly thinks you clicked the item on the left.

![image](https://user-images.githubusercontent.com/59719612/211054597-783fa56c-345b-42ec-b343-e24158aff0a7.png)
