### ISSUE TITLE
Inaprovaline and Carbon can still react in body to make Bicaridine

### ISSUE THREAD

**Issue by warface1234455** [cmss13-devs/cmss13#2302]
### Testmerges

#2203, #2244, #2100, #2163, #2273

### Description of the bug

Title

### What's the difference with what should have happened?

It shouldn't do this because inaprovaline stops reactions while inside body

### How do we reproduce this bug?

1. get inaprovaline
2. get carbon
3. Inject all inside a body
4. OH SHIT BICARIDINE IS MADE

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Segrain** [comment]
"Inaprovaline stops reactions while inside body" is _not a thing_. It is not meant to be a thing. I do not know who started this rumour and how.
_Why_ are you feeding somebody carbon anyway...?

**Comment by warface1234455** [comment]
> "Inaprovaline stops reactions while inside body" is _not a thing_. It is not meant to be a thing. I do not know who started this rumour and how. 

 It's on wiki that said so


>_Why_ are you feeding somebody carbon anyway...?

 Well i just notice this

**Comment by Segrain** [comment]
> It's on wiki that said so, even ina and dylo couldn't react together to make tc while inside body
Then the wiki was written by somebody with no idea what he is saying. Tricordrazine, by design, does not react in the humans in our handholding code, because you are actually _expected_ to feed humans both inaprovaline and dylovene, and back in old days medbay knew to not feed both at once, but we cannot expect barest minimum of competence nowadays, so somebody coded it to not happen. It does not mean that inaprovaline prevents any other reactions.
Still _might_ have to do something about this, for mostly unrelated reasons, so leaving this open as a reminder to myself.

**Comment by Huffie56** [comment]
![image](https://user-images.githubusercontent.com/117036822/236629825-be59df08-1c4a-4a57-aaa3-0f89f5f02bcc.png)
https://cm-ss13.com/wiki/Chemistry
