### ISSUE TITLE
Ointment doesn't actually heal 5 burn damage

### ISSUE THREAD

**Issue by Sargeantmuffinman** [cmss13-devs/cmss13#3058]
### Testmerges

#2964, #3039, #3040, #3052

### Description of the bug

As per title.

### What's the difference with what should have happened?

Well, it should.

### How do we reproduce this bug?

1. Take burn damage.
2. Scan yourself.
3. Heal yourself with ointment.
4. See that it only heals one burn damage.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
Ointment never healed 5 burn damage per use. Advanced burn kits DO heal 5 burn damage from non-medically trained marines just as ATKs heal 5 brute. If ointment healed 5 burn damage per use, there would be no reason for a non-medically trained marine to ever use an advanced burn kit. Further, the ointment actually ends up healing a bit more than 1 burn per use because once the area is treated, it begins healing itself slowly similar to bandages.

**Comment by TeDGamer** [comment]
> Ointment never healed 5 burn damage per use. Advanced burn kits DO heal 5 burn damage from non-medically trained marines just as ATKs heal 5 brute. If ointment healed 5 burn damage per use, there would be no reason for a non-medically trained marine to ever use an advanced burn kit. Further, the ointment actually ends up healing a bit more than 1 burn per use because once the area is treated, it begins healing itself slowly similar to bandages.

https://github.com/cmss13-devs/cmss13/pull/3025

Not sure if you saw the changelogs, but this was approved and merged. 

Made a fix for this.

**Comment by ItsVyzo** [comment]
thanks for le fix, it worked during testing so kinda confused now qq
