### ISSUE TITLE
Acid Spray doesn't extinguish the target consistently. (unless they are standing still)

### ISSUE THREAD

**Issue by gitbirb** [cmss13-devs/cmss13#3412]
### Testmerges

#3088: 'Fixes offset issue for multithreading test' by LynxSolstice at commit 95d6c01a9c #3298: 'Project ARES - Resurrection' by realforest2001 at commit 936e671eb9 #3271: 'Pred QOL updates' by realforest2001 at commit 7e959ad32f #3185: 'GAU buff. ' by Tisx1 at commit 341378a5af #3223: 'CMB Black Market Investigation' by BeagleGaming1 at commit b80a33bb14 #3398: 'Aim mode removal' by morrowwolf at commit 168ffa6bc1

### Description of the bug

This is an inconsistency because acid spray is not calculated like most projectiles, yet extinguishing only happens on direct hit: completely making no sense with the method (sloooow and you can walk through it)

Spray column direct hits are jank. You need to be on the tile when the _spray is formed_, or you wont be direct hit, as opposed to being able to walk "through" the path of the projectile, and get direct hit. 

### What's the difference with what should have happened?

If Z (person) walks through the path of line X (acid spray), they should intersect, and thus output a direct hit. :

If it works consistently it should work like:

tile A being where spray hit previously, tile B being where spray hits next:
walk through line A-B you will get direct hit  (extinguished)

while im not sure if this is the EXACT problem, i do think its something to do with this. The projectile is slow, so it is easy to dodge in this way even on accident.
### How do we reproduce this bug?

1. be spitter,prae,boiler
2. acid spray a person on fire in a 1 tile hall.
3. that person moves towards you to get to the acid spray sooner
4. they end up not extinguished whatsoever, even though it should have hit them.
5. as a result, they're still on fire! Oh no!
...

### Issue Bingo

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Huffie56** [comment]
@gitbirb when you say acid spray a person you mean a xeno? or a marine?

**Comment by Drulikar** [comment]
I understand what you mean but this would be a huge buff to spitters and some praes effectivelly making the spray effectively two tiles wide rather than one. A think a compromise would be if you direct click the ability on a target, you get 1 extra tile of buffer to hit them. As in you sprite click spray someone 4 tiles away, if they move no more than 1 tile they will still be hit. I think this compromise gives more focus to be succesfully extinguishing allies over fast moving marines (you typically need to lead your target for them), but would also help the abilitiy to land on marines that are slow.

**Comment by Drulikar** [comment]
Completed?
