### ISSUE TITLE
Weed nodes can be placed under window frames

### ISSUE THREAD

**Issue by Time-Warper** [cmss13-devs/cmss13#3770]
### Testmerges

#3601: 'InfluxDB Metrics Backend' by fira #3644: 'The weeds are hungry: Bodies for the weeds' by Drulikar #3676: 'New Varadero revamp' by AnuvKH  #3690: 'gives all xenos access to the (xeno) tacmap while the queen is on ovi' by harryob  #3755: 'Bioscan Logging & Efficiency Upgrades' by realforest2001 #3525: 'Port /tg/ PR #75835 - Linux 515 fcopy() crash fix' by fira

### Description of the bug

You can place weed node under window frames. It worked in the new map: New Varadero. I haven't tried it in other maps yet.

### What's the difference with what should have happened?

The weed node is completely hidden when doing this. It doesn't seem fair.

### How do we reproduce this bug?

1.Stand on frame
2.Place weed node
3.
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
Alright look, there are MANY objects weed nodes can be placed to hide under said objects. Vendors, barricades of all kinds, dead xenos, lockers, etc, etc. At some point you just start cutting into the nuance of planting weeds around the map and degrade the play experience for drones and marines by simply blocking the nodes. Learning where good weed node locations are to plant and to search for to break is part of becoming a good CM player.

**Comment by Wintermote** [comment]
It's unintuitive (frankly 100% unintended) behaviour and in cases like weed nodes under resin walls, doors, window frames, etc. you cannot ever even click on the weed node without either knowing the alt+lmb on adjacent tile and clicking in the system tab on the object trick (virtually nobody knows about this), or destroying the object the node is under first and then the node itself.

There may even be some objects that cover the whole tile you can't destroy at all.

It's an exploit that's become endemic with the playerbase due to existing for so long. I understand some people think it's nice to add more protection to nodes but it's not fun or interesting to deal with. If nodes need more protection for whatever reason it should be introduced as an actual intended gameplay mechanic.

The simplest solution is probably specialized sprites for these given objects such that the weed node is destroyed on hits first, and then the underlaying object, rather than the underlaying object and then the node.

**Comment by Superwelder** [comment]
> It's unintuitive (frankly 100% unintended) behaviour and in cases like weed nodes under resin walls, doors, window frames, etc. you cannot ever even click on the weed node without either knowing the alt+lmb on adjacent tile and clicking in the system tab on the object trick (virtually nobody knows about this), or destroying the object the node is under first and then the node itself.
Weed node hunting is intuitive though. The average person seeing weeds grow from a node will deduce that breaking the node breaks the weeds and/or stops the weeds from growing. It is understandable not to want the node occupying a wall tile since a wall occupies all the tile's space but a door or window sill? Players can move into those spaces. A player actually can target nodes under doors by hitting the outside of the tile not covered by the door sprite. Its even easier to hit a node on a window sill. Right clicking to find where hidden nodes are promotes learning that players can then apply to things like looking for resin holes, resin spikes, huggers, valuable loot, etc. Its part of the soul of the game for better and for worse.
