### ISSUE TITLE
Emergency Auto Injector Is Refillable

### ISSUE THREAD

**Issue by Steelpoint** [cmss13-devs/cmss13#3980]
### Testmerges

#3783: #3955: #3962:#3917:#3909:#3843:#3902:#3974:

### Description of the bug

When you select a used emergency auto injector, you can refill it on a Wey-land Plus vendor, hacked or unhackced. 

I tested this on the live server and on a offline up-to-date version of the code as well. . 

### What's the difference with what should have happened?

The emergency injector should not be refillable. 

### How do we reproduce this bug?

1. Grab a used injector
2. Click a Wey-Land Plus vendor to refill it
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Wintermote** [comment]
There's two types of emergency injectors, one comes in the PFC medical pouch and is an EZ emergency autoinjector (it is colored green), this cannot be refilled in any of the aforementioned vendors etc.

The second type of emergency injector requires medical skill to use properly and is tan colored. Squad leaders get them out of their autoinjector pouches. These tan colored emergency injectors can be refilled in wall vendors etc.

I don't know whether it's intentional design, but it's worth pointing out anyway

**Comment by Steelpoint** [comment]
I only noticed this when playing as a SL so this is the case.  Question is then if this is intended behaviour or unintentional.

**Comment by Huffie56** [comment]
> Will take care of this whenever I will get to taking the planned look at emergency injectors in general (I have _opinions_.)

Lorax was interested in fixing this issue. don't know how far he is on it... will tell him.

**Comment by Huffie56** [comment]
i tried to reproduce with the standart refillable autoinjector everyone get and the other one that cost point to get for spe but was unable to refill them.
i don't see how i would have miss that test so closing it now.

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/4167
this is probably the PR that fix it...
