### ISSUE TITLE
Vending Machines Ate All My Money

### ISSUE THREAD

**Issue by RavinHobo** [cmss13-devs/cmss13#4543]
### Testmerges

d186d8446bd39a091ce3d5a711697c6822932367

### Description of the bug

When paying for an item through a vending machine with cash in hand it uses all of the money in your hand instead of the required amount. I PAID 14K FOR A FUCKING PLASTIC WRAPPED BURGER AND I DIDN'T EVEN EAT THE BURGER RAHHHH.

### What's the difference with what should have happened?

not eat 14k

### How do we reproduce this bug?

1.no money in account
2.cash in hand
3.buy item
4.14k gone

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
It's 2182 and the use exact change light is burnt out.

(When I added the ability for them to accept cash, I intentionally implemented it where they don't return any change and tell you to contact your supervisor. Sort of intended to create maybe a funny experience to talk to others in game about - especially since money isn't currently persistent for it to actually matter. )

**Comment by RavinHobo** [comment]
ah didnt see that message
