### ISSUE TITLE
i spawned with a CLF uniform and an ID called Survivor

### ISSUE THREAD

**Issue by TTaxer** [cmss13-devs/cmss13#5311]
### Testmerges

#5086, #5298, #5289, #5246 #5007 #5113

### Round ID

20126

### Description of the bug

I rolled survivor and i spawned with a CLF uniform and an ID called survivor, i am not CLF
![image_2023-12-27_003742934](https://github.com/cmss13-devs/cmss13/assets/121460190/ec981b91-24d8-49ce-9c87-5a0f36d2c705)

### What's the difference with what should have happened?

Not spawn with a CLF uniform while im not CLF

### How do we reproduce this bug?

1.Roll Survivor
2.Spawn In
3.Spawn with a CLF uniform, Sometimes??
...

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by BadAtThisGame302** [comment]
Well, yes. You spawned with a CLF uniform, CLF random armor(?) and I assume a CLF headset. So yes, you are a CLF survivor. The ID on CLF surv doesn't say CLF Soldier, that's be too easy, it says survivor because I personally think that you can use the obscurity of the "survivor" ID to dress up as anyone and pretend to be someone you're not to avoid the marines shooting you in the face.

**Comment by TTaxer** [comment]
it didnt mention i was CLF

**Comment by TTaxer** [comment]
also not CLF armor

**Comment by ItsVyzo** [comment]
You spawn with CLF uniform means you are CLF. This is NOT a bug. It stating you are non-hostile is a bug.
