### ISSUE TITLE
Sentries will attempt to shoot huggers in pipes

### ISSUE THREAD

**Issue by Megaddd** [cmss13-devs/cmss13#5556]
### Testmerges

#5086, #5392, #5452, #5405, #5536, #5526, #5506

### Round ID

20571, 20583

### Description of the bug

Comtech and Dropship sentries will endlessly expend ammunition attempting to hit a facehugger that is calmly running around inside vents pipes.

### What's the difference with what should have happened?

Sentries ignore things they cannot hit in pipes.

### How do we reproduce this bug?

~~1. Put a sentry on Alamo~~ (doesn't appear to always work)
1b. Try using a comtech turret instead
2. Run a hugger in vents past it

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Drulikar** [comment]
https://cdn.discordapp.com/attachments/862155128441012234/1200268305651482786/ultraturret1.mp4?ex=65c58ff7&is=65b31af7&hm=e99199eacfef6a1120ad8b2334e82b1da325311e9cd8702b5530c0d43baeff35& likely also applies to equipped sentries?

**Comment by Vicacrov** [comment]
I could not reproduce this with the UA-571-C sentry gun (placed it on the Alamo, activated it, ran in front of it with a hugger, it shot it. I spawned another hugger, climbed into a vent, went up to it in the vent, it was not shooting at it).

**Comment by RenaRenaRe** [comment]
I am also unable to reproduce locally, I even tested it in the exact same spot on Sorokyne and it still didn't work. However I can confirm this definitely did happen because I was playing lesser drone that round and was crawling around the vents in the fob. In fact it is I that was blown up by that sentry in the clip Drulikar posted.
Both the dropship sentries and a plasma sentry were attempting to shoot at my position despite me being in a vent. Strangely the plasma sentry also started shooting _backwards_ when I moved in front of it and then moved behind, as if it didn't care about the angle for some reason.
At the time I did think it was strange because in other rounds prior I had vented in front of sentries and had never seen this behaviour before. So seems like something was broken that round and I have no idea what. Maybe that get_line() refactor testmerge?

**Comment by Megaddd** [comment]
https://github.com/cmss13-devs/cmss13/assets/8878624/4186c568-e9a0-4bcb-9a89-276b1efccbf5

**Comment by Superwelder** [comment]
HIGHLY related problem, was put inside a host as larva during hijack and the person was near a fuel pump. All the sentries at the fuel pump targeted me as a larva inside the host with constant fire. As in non-stop firing at the infected person, very quick corpse. I was able to stay inside the body for some time as the sentries just kept firing. I seriously doubt sentry guns have the ability to identify larva inside a person in lore or they would be shooting any infected person on sight. Do not know if engineer based sentries do the same thing.

**Comment by GrrrKitten** [comment]
Happened in Round ID 20808 with lessers in pipes

**Comment by Huffie56** [comment]
https://github.com/cmss13-devs/cmss13/pull/6223
this PR should fix this issue.
ask for it to be reopen if it doesn't.
