### ISSUE TITLE
Xenos Sometimes Die When Dragged on Weeds in Critical State.

### ISSUE THREAD

**Issue by Venuska1117** [cmss13-devs/cmss13#6090]
### Testmerges

N/A it exist for long time

### Round ID

21633

### Description of the bug

Wardening And Xenos in Critical can sometimes suddenly die when dragged on weeds while they are at critical.

(i didnt hear them getting stabbed by scout knife or get shooted by bullet)

### What's the difference with what should have happened?

They should keep get healed, because they are on weeds.

### How do we reproduce this bug?

1. Be gardener drone.
2. Have wardening on.
3. Ravager get to low critical (something around -90%)
4. Give Ravager greather resin fruit.
5. Make it gone back to low critical again.
6. Drag Ravager trough weeds when they are around -10% (?) health (they close going out of critical)
7. Ravager suddenly die from critical (?) when you drag them on weeds.

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by ihatethisengine** [comment]
It can happen when they lose warding (or when warding becomes weaker).

**Comment by Venuska1117** [comment]
> It can happen when they lose warding (or when warding becomes weaker).

issue is, i had moderate and rav was fine with critical, so why sudden change ( i didnt notice but maybe it was strong for moment) killed it, when it was fine on moderate?

**Comment by ihatethisengine** [comment]
Are you absolutely sure no one provided the rav strong or very strong warding? Like queen, healer drone or warden. Also are you sure you didn't run out of plasma and didn't lose pheros? I am just trying to narrow down the suspects, but honestly if they died of warding loss it's not a bug, but still something that probably should be changed.

**Comment by Diegoflores31** [comment]
loosing warding makes them die because warding gives them more crit window but since they lost it they die

**Comment by Superwelder** [comment]
> loosing warding makes them die because warding gives them more crit window but since they lost it they die. normally you die as a xeno on -100 . but for example a queen warding could get you dunno -400 lets say ( i dont know the exact number) thne when you loose it if you are still lower than -100 you will die instantly . and it is intended

After testing around a bit, I think there may actually be a bug here but the author of this issue did not describe it correctly. It is true that if a xeno loses warding pheros while in crit they can simply drop to a lethal threshold and die in an instant. HOWEVER, if a xeno has say, strong warding and gets swapped to medium warding, in the process of transferring to the medium warding, a xeno can just die as if they were dropped to 0 warding before re-adding the medium warding which could have saved them. This process may be reversible as well which is much more common as stronger phero types override weaker types. A queen with very strong warding may inadvertently be killing a xeno by moving into an area that a xeno being kept alive with weaker pheros is in since they override those weak pheros for her strong pheros and, in the process, set the xeno to zero warding pheros before her strong pheros get applied saving the xeno again. I am not sure if this is the exact cause of what is going on but there is definitely something funky going on with warding pheros causing xenos to just die. Since some warding can come from offscreen it is entirely possible this bug was not found because it is very hard to notice as you play.

**Comment by Drulikar** [comment]
The only way I can see something like that occurring is if the xenomorph global list rearranges mid game. But I don't see any indication of it getting sorted or re-arranged. You just have xenos removed when they die, and added when they are born. `/mob/living/carbon/xenomorph/proc/handle_pheromones()` handles the potential for phero givers to be before or after the xeno by having a new and real value for each phero.

If the phero giver occurs later than this xeno, we still get their pheros from last tick because they changed our "new" value after this xeno. It just means it takes 1 additional tick for us to get the benefit of the phero, but it also lasts 1 additional tick when they no longer give it to us.

If the phero giver occurs before this xeno the "new" value is replaced before this xeno. So this means we don't get that 1 tick lag.

The application of phero strength is checking if the applied value is larger than the existing "new" value.  So gaining a strong phero doesn't mean you have a tick of no pheros. When the "new" value is converted to the real value, the HUD is updated so you should see the UI reflect every phero change.
