### ISSUE TITLE
Xeno Corpses Consumed By Weeds Glitching Out

### ISSUE THREAD

**Issue by Superwelder** [cmss13-devs/cmss13#6220]
### Testmerges

#5401, #6103, #5957, #6148, #6039, #6150, #6146, #6178, #6212, #6155

### Round ID

21993 - Recon Tango-Golf

### Description of the bug

![image](https://github.com/cmss13-devs/cmss13/assets/105765670/448dc26d-f833-45be-8f2b-ac83546a2d32)
![image](https://github.com/cmss13-devs/cmss13/assets/105765670/ba2cb1a0-24ee-4d41-9c23-05f4a206a733)

Xenos consumed by weeds after being dead on a weeded tile for some time can be 'moved' by the force of an explosion but if the weed under them is not broken, they stay in this weird limbo where you can not drag them, shoot them, punch them, etc. In this case there are no other weeds around and this runner corpse is still covered in weeds.

### What's the difference with what should have happened?

Corpses should not bug out to the point of not being able to interact with them in any way. Unfortunately I can not replicate this bug on demand but am seeing it quite often round to round.

### How do we reproduce this bug?

This is how the bug happened as I saw it for the screencaps above but could be related to something entirely different.
1. Have weed-consumed xeno corpse.
2. Move the corpse via explosives in such a way that the weeds under it do not break.
3. Scratch your head.

### Issue Bingo

- [ ] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Superwelder** [comment]
Oh forgot to add, when using alt + click to see the tile contents of the tile with the weed-covered runner in the pictures, the panel had no such corpse noted. Actually nothing was on the tile.

**Comment by Drulikar** [comment]
Not showing up in alt click is intentional; They also don't show up in right click, nor respond to left click, nor show up in the hover text on the bottom left. They are "transparent" to the mouse.

However I am not able to reproduce this issue. Nor do I see any related runtime in that round.

When you become weeded, you become anchored. Additionally, even if I edit their anchored variable, drop a bomb on them (had to make the weeds very healthy and the corpse very healthy to not destroy/gib) they unweed when they are moved since I have a signal for movement here: https://github.com/cmss13-devs/cmss13/blob/master/code/datums/components/weed_food.dm#L117-L119

![bomb](https://github.com/cmss13-devs/cmss13/assets/76988376/2ca9ece4-3773-4564-8263-b2405ab0835d)

**Comment by Superwelder** [comment]
Very interesting. The situation with the pics I grabbed was the Alamo had crashed into the Brig, marines pushed into the Alamo to take the core down. HEDPs were being thrown left and right and I saw this weeded runner corpse moving with the explosions. I was curious and tried to break weeds on it but none existed. I then tried to move it and could not. I wish I had another HEDP or I would have tested that. I did also see these corpses moving groundside so maybe something happened in round to unlock this behavior? Sorry for making you test it to no success. Just had not seen this behavior in rounds before this one.

**Comment by Drulikar** [comment]
Mentioned it to you in DMs, but just for others this is likely also the same problem, but I do not know how to reproduce it: https://discord.com/channels/150315577943130112/964684928161808384/1191195372266197094
![image](https://github.com/cmss13-devs/cmss13/assets/76988376/65ea2da7-3058-4dd9-8392-9482d01fbaa3)
