### ISSUE TITLE
larvas are inmortal

### ISSUE THREAD

**Issue by Diegoflores31** [cmss13-devs/cmss13#7082]
### Testmerges

consistent bug

### Description of the bug

larvas under the effect of warding pheromones are inmortal.
this has been an issue since a lot of time . its just that its very unfrequent that a larva happens to get shot in the front as per gameplay rules but its starting to happen somewhat frequently.

### What's the difference with what should have happened?

larva dies after getting shot in crit.

### How do we reproduce this bug?

1.give a larva warding pheros
2.try to kill
3. it doesnt die
...

### Issue Bingo

- [X] Issue could be reproduced at least once
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Diegoflores31** [comment]
https://github.com/user-attachments/assets/e32fe9e6-d3fb-409c-bd7f-175214d5cd80

**Comment by Diegoflores31** [comment]
that is a video from 2022 just to show this been an issue from god knows when

**Comment by Red-byte3D** [comment]
What's probably happening here is that the larva has its own crit_health = -35 var which also gets checked by the same xenomorph var in general, which is -100 and im assuming the warding code checks for the -100 + warding phero strength, and untill you get to - 100 + warding phero strength you arent killed because the warding would save you, but because the larva max crit is -35 its just not being processed further so they're immortal

**Comment by Diegoflores31** [comment]
> What's probably happening here is that the larva has its own crit_health = -35 var which also gets checked by the same xenomorph var in general, which is -100 and im assuming the warding code checks for the -100 + warding phero strength, and untill you get to - 100 + warding phero strength you arent killed because the warding would save you, but because the larva max crit is -35 its just not being processed further so they're immortal

It could be this but i have seen people complaining about this same issue happening with other castes
