### ISSUE TITLE
Tunnel exploit, can place traps and resin nodes, unable to see either underneath.

### ISSUE THREAD

**Issue by TheeBiggest** [cmss13-devs/cmss13#805]
## Description
Playing as a Synthetic, I found a tunnel, weeds around. I assumed the node was underneath. Hitting it revealed an acid trap activating. There was no indication the trap was there. There was no way for me to safely disarm it. The trap tile hides resin nodes.

## Difference between expected and actual behavior
Tunnels should NOT be able to hide resin holes aka traps AND traps should NOT be able to hide resin nodes, combing all 3 is an exploit.

## Issue bingo (not required to be all checked)

- [x] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

https://imgur.com/a/CjN9xyF

## Resolution

Make it so all 3 are unable to be placed on top of each other, or nearby each other. Same with how recovery nodes work being unable to be placed by walls, have that apply with traps unable to connect to nodes and/or tunnels, separation from each other.

**Comment by Superwelder** [comment]
I can confirm the burrower tunnels covering a resin trap as a real issue but for the love of queen mother, do not remove the ability to place resin traps over resin nodes. There is no current way for a burrower or carrier to remove a resin node in order to place a trap in that position. The current system with resin holes covering resin nodes is far more tolerable than the reverse and a synth trying to hit the node underneath unintentionally hitting the resin hole is such an extreme edge case. The removal of which would seriously harm burrower and carrier efficacy in a round.

**Comment by Diegoflores31** [comment]
I was unable to reproduce the bug . placing a tunnel on top of a trap breaks the trap instantly and you cant place a trap on top of a tunnel . please provide clearer instructions

**Comment by Diegoflores31** [comment]
already fixed but geeves did not linked this lmao
#810

**Comment by morrowwolf** [comment]
HYPOTHETICALLY FIXED BY #810
